version: "3.9"

services:

  postgres:
    container_name: nest-access-control-db
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - nest_app_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - nest
    ports:
      - 5432:5432

volumes:
  nest_app_database:
  nest_app_pgadmin:


networks:
  nest:
    driver: bridge
