export const PERMISSIONS_FEATURE_OPTIONS = 'PERMISSIONS_FEATURE_OPTIONS';

export const PERMISSIONS_GUARD_CONFIG = 'PERMISSIONS_GUARD_CONFIG';

export const PERMISSIONS_ACTION_TYPE = 'PERMISSIONS_ACTION_TYPE';
